### ISSUE TITLE
false testimonial in android app store

### ISSUE THREAD

**Issue by ryancdotorg** [HashEngineering/namecoin-wallet#1]
In your description in the android app store, you claim

> TESTIMONIALS
> • Recommended mobile wallet by http://namecoin.org/

No such recommendation exists, please remove this claim.

**Comment by HashEngineering** [comment]
You are correct.  Thank you for pointing this out.  The Google Play Store Listing text has been updated to remove the Testimonials section.

**Comment by ryancdotorg** [comment]
Thank you. It looks like maybe this happened unintentionally due to a search-and-replace on another description.

**Comment by HashEngineering** [comment]
Yes, it was a search and replace.
